# Configuration for diun setup

# Name of the big-bear-diun application
name: big-bear-diun

# Service definitions for the big-bear-diun application
services:
  # Service name: big-bear-diun
  # The `big-bear-diun` service definition
  big-bear-diun:
    # Name of the container
    container_name: big-bear-diun

    # Image to be used for the container
    image: crazymax/diun:4.28.0

    # Command to run inside the container
    command: serve

    # Container restart policy
    restart: always

    # Environment variables for the container
    environment:
      - TZ="UTC"
      - DIUN_WATCH_WORKERS="20"
      - DIUN_WATCH_SCHEDULE="0 */6 * * *"
      - DIUN_WATCH_JITTER="30s"
      - DIUN_PROVIDERS_DOCKER="true"

    # Volumes to be mounted to the container
    volumes:
      - /DATA/AppData/$AppID/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - diun.enable=true

    x-casaos: # CasaOS specific configuration
      envs:
        - container: TZ
          description: "Timezone"
        - container: DIUN_WATCH_WORKERS
          description: "Number of workers"
        - container: DIUN_WATCH_SCHEDULE
          description: "Watch schedule"
        - container: DIUN_WATCH_JITTER
          description: "Watch jitter"
        - container: DIUN_PROVIDERS_DOCKER
          description: "Enable Docker provider"
      volumes:
        - container: /data
          description: "Container Path: /data"
        - container: /var/run/docker.sock
          description: "Container Path: /var/run/docker.sock"

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm64
  # Main service of the application
  main: big-bear-diun
  description:
    # Description in English
    en_us: "Docker Image Update Notifier is a CLI application written in Go and delivered as a single executable (and a Docker image) to receive notifications when a Docker image is updated on a Docker registry."
  tagline:
    # Short description or tagline in English
    en_us: "Docker Image Update Notifier"
  # Developer's name or identifier
  developer: "crazymax"
  # Author of this configuration
  author: BigBearTechWorld
  # Icon for the application
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/diun.png?raw=true
  # Thumbnail image (currently empty)
  thumbnail: ""
  title:
    # Title in English
    en_us: "Docker Image Update Notifier"
  # Application category
  category: BigBearCasaOS
